src/dashboard/urls.py
from django.urls import path
from django.urls.conf import include

from dashboard.views import UserAutoComplete, account, dashboard_view

app_name = "dashboard"

urlpatterns = [
    path("", dashboard_view, name="home"),
    path("account/", account, name="account"),
    path("users/", UserAutoComplete.as_view(), name="user-autocomplete"),
]

src/events/urls.py
from django.urls import path

from events.views import (CategoryAutoComplete, EventAction, EventCreate,
                          EventDelete, EventDetail, EventList, EventUpdate,
                          PostcodeAutoComplete)

app_name = 'events'

urlpatterns = [
    path("categories/",
         CategoryAutoComplete.as_view(),
         name="category_autocomplete"),
    path("postcodes/",
         PostcodeAutoComplete.as_view(),
         name="postcode_autocomplete"),
    path("create/", EventCreate.as_view(), name="event_create"),
    path("<int:pk>/", EventDetail.as_view(), name="event_detail"),
    path("<int:pk>/action/", EventAction.as_view(), name="event_action"),
    path("<int:pk>/update/", EventUpdate.as_view(), name="event_update"),
    path("<int:pk>/delete/", EventDelete.as_view(), name="event_delete"),
    path("", EventList.as_view(), name="event_list"),
]

src/news/urls.py
from django.urls.conf import path

from news.views import NewsItemDetail, NewsItemList

app_name = "news"

urlpatterns = [
    path("<int:pk>/", NewsItemDetail.as_view(), name="newsitem_detail"),
    path("", NewsItemList.as_view(), name="newsitem_list"),
]

src/proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('django_auth_oidc.urls')),
    path('app/', include("dashboard.urls")),
    path("app/events/", include("events.urls", 'events')),
    path("app/news/", include("news.urls", 'news')),
    path("app/tasks/", include("tasks.urls", 'tasks')),
    path('', include("events.external_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/tasks/urls.py
from django.urls import path

from tasks.views import TaskDetail, TaskList

app_name = 'tasks'

urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("<int:pk>/", TaskDetail.as_view(), name="task_detail"),
]

src/dashboard/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from ordered_model.models import OrderedModel

# Create your models here.


class Application(OrderedModel):
    """Application that activists can access with their login."""
    url = models.URLField(verbose_name=_("url"))

    name = models.CharField(max_length=255, verbose_name=_('name'))
    description = models.TextField(verbose_name=_("description"))
    image = models.ImageField(upload_to='apps/', verbose_name=_("image"))

    class Meta(OrderedModel.Meta):
        verbose_name = _("application")
        verbose_name_plural = _("applications")

    def __str__(self):
        return self.name

src/dashboard/views.py
from dal import autocomplete
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Value as V
from django.db.models.expressions import F, Value
from django.db.models.functions import Concat
from django.db.models.query_utils import Q
from django.shortcuts import render
from django.utils.html import escape

from events.models import Event
from tasks.models import PUBLISHED, Task

# Create your views here.


@login_required
def dashboard_view(request):

    return render(
        request, 'dashboard/home.html', {
            'tasks':
            Task.objects.filter(participants=request.user, state=PUBLISHED),
            'events':
            Event.objects.filter(
                Q(owner=request.user) | Q(managers=request.user))
        })


@login_required
def account(request):
    return render(request, "dashboard/account.html", {})


class UserAutoComplete(autocomplete.Select2QuerySetView):
    def get_result_label(self, result):
        return escape(f"{result.first_name} {result.last_name}")

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return get_user_model().objects.none()

        if self.q and len(self.q) > 2:
            return get_user_model().objects.annotate(
                full_name=Concat("first_name", V(" "), "last_name")).filter(
                    full_name__icontains=self.q).exclude(
                        pk=self.request.user.pk).order_by('last_name')

        return get_user_model().objects.none()

src/dashboard/templates/dashboard/account.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block breadcrumbs %}
<a href="{% url 'dashboard:account' %}">{% trans 'Profile' %}</a>
{% endblock %}

src/dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="{{request.LANGUAGE_CODE}}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}" />
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}" >
    {% block styles %}
    {% endblock %}
  </head>
    <body>
      <aside id="sidePanel" data-open="true">
        {% include 'dashboard/side_panel.html' %}
      </aside>

      <div class="container">
        <main id="pageContent" data-title="{% block title %}{{title}}{% endblock %}">
          <header class="topBar">
            <div class="breadcrumbs">
              {% block breadcrumbs %}
              {% endblock %}
            </div>
            <div class="actionGroup">
              {% block actions %}
              {% endblock %}
            </div>
          </header>
          <div class="messages">
            {% if messages %}
            <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %} onclick="this.remove()">{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %}
          </div>
          {% block page_content %}
          <!--- Here comes the content of the page -->
          {% endblock %}
        </main>
        <section id="appBar">
          <button id="menuToggle" type="button">
            <i data-feather="menu"></i>
          </button>
          <section id="appList">
            {% for app in applications %}
            <a title="{{app.description | safe}}" class="appLink" target="_blank" href="{{app.url}}"><img class="appImage" src="{{app.image.url}}" /> <span>{{app.name}}</span></a>
            {% endfor %}
          </section>
          <!--- Button for opening and closing the navigation + list of apps-->
        </section>
      </div>
      <script src="https://unpkg.com/htmx.org@1.2.1" integrity="sha384-t37OW0DbqgL50XZW+Tl8TLchxsPoxIJ7NQ/l4aSZIXZVJQAhyQvvkWZgL/SiY/jD" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
      <script src="{% static 'dashboard/dashboard.js' %}"></script>
      {% block scripts %}
      {% endblock %}
    </body>
</html>

src/dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Home' %}{% endblock %}


{% block page_content %}

<h2>{% trans 'Your Tasks' %}</h2>

<h2>{% trans 'Apps' %}</h2>

{% endblock %}

src/dashboard/templates/dashboard/page.html
{% extends 'dashboard/base.html' %}

{% block page_content %}
<div class="content_head">
  <section id="breadcrumbs">
    {% block breadcrumbs %}{% endblock %}
  </section>
  <section id="quickActions">
  </section>
</div>
<div class="content">
  <h1>{% block title %}{% endblock %}</h1>
  {% block content %}{% endblock %}
</div>
{% endblock %}

src/dashboard/templates/dashboard/side_panel.html
{% load i18n static %}
<header>
  <img src="{% static 'logo.png' %}" alt="Logo" />
</header>
<nav id="mainNav">
  <a href="{% url 'dashboard:home' %}"><i data-feather="home"></i> {% trans 'Home' %}</a>
  <a href="{% url 'events:event_list' %}"><i data-feather="calendar"></i> {% trans 'Events' %}</a>
  <a href="{% url 'tasks:task_list' %}"><i data-feather="check"></i> {% trans 'Tasks' %}</a>
  <a href="{% url 'news:newsitem_list' %}"><i data-feather="globe"></i> {% trans 'News' %}</a>
</nav>