src/news/urls.py
from django.urls.conf import path

from news.views import NewsItemDetail, NewsItemList

app_name = "news"

urlpatterns = [
    path("<int:pk>/", NewsItemDetail.as_view(), name="newsitem_detail"),
    path("", NewsItemList.as_view(), name="newsitem_list"),
]

src/proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('django_auth_oidc.urls')),
    path('app/', include("dashboard.urls")),
    path("app/events/", include("events.urls", 'events')),
    path("app/news/", include("news.urls", 'news')),
    path("app/tasks/", include("tasks.urls", 'tasks')),
    path('', include("events.external_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/tasks/urls.py
from django.urls import path

from tasks.views import TaskDetail, TaskList

app_name = 'tasks'

urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("<int:pk>/", TaskDetail.as_view(), name="task_detail"),
]

src/tasks/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.

DRAFT = 0
PUBLISHED = 3
DONE = 5

TASK_STATES = (
    (DRAFT, _("draft")),
    (PUBLISHED, _("published")),
    (DONE, _("done")),
)


class Topic(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField()

    title = models.CharField(max_length=255)
    description = RichTextField()

    issuer = models.ForeignKey(get_user_model(), models.CASCADE)

    state = models.IntegerField(choices=TASK_STATES, default=DRAFT)

    topics = models.ManyToManyField(Topic, blank=True)

    participants = models.ManyToManyField(get_user_model(),
                                          related_name="assigned_task_set",
                                          blank=True)

    rocket_chat = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

src/tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model


class SelectUserForm(forms.Form):
    user = forms.ModelChoiceField(get_user_model().objects.all())

src/tasks/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from dashboard.utils import ActionView
from tasks.actions import CloseTask, JoinTask, LeaveTask, RemoveUserFromTask
from tasks.models import Task

# Create your views here.


class TaskList(ListView):
    model = Task
    paginate_by = 20


class TaskDetail(DetailView):
    model = Task


class TaskActionView(ActionView):
    model = Task

    actions = {
        'join': JoinTask,
        'leave': LeaveTask,
        'close': CloseTask,
        'remove': RemoveUserFromTask
    }

src/tasks/templates/tasks/task_detail.html
{% extends 'dashboard/base.html' %} {% load i18n l10n %}

{% block title %}{{task.title}}{% endblock %}


{% block breadcrumbs %}
<a href="{% url 'tasks:task_list' %}">{% trans 'Tasks' %}</a> / <a href="{% url 'tasks:task_detail' task.pk %}">{{task.title}}</a>
{% endblock %}

src/tasks/templates/tasks/task_list.html
{% extends 'dashboard/base.html' %}
{% load i18n l10n %}

{% block title %}{% trans 'Tasks' %}{% endblock %}

{% block breadcrumbs %}
<a href="{% url 'tasks:task_list' %}">{% trans 'Tasks' %}</a>
{% endblock %}

{% block page_content %}
<form method="get" id="filterForm" action="">
  {% for field in filter_form %}
  <div class="formField">
    <label>{{ field.label }}</label>
    {{ field }}
  </div>
  {% endfor %}
  <button type="submit">Los</button>
</form>

<article id="eventList" class="tasks">
  <table class="taskTable">
    <thead>
      <th>
        <td>
          {% trans 'Title' %}
        </td>
        <td>
          {% trans 'Created' %}
        </td>
        <td>
          {% trans 'Deadline' %}
        </td>
        <td>
          {% trans 'Topics' %}
        </td>
      </th>
    </thead>
    <tbody>
      {% for task in task_list %}
      <tr>
        <td><a href="{% url 'tasks:task_detail' task.id %}">{{task.title}}</a></td>
        <td>{{task.created_at}}</td>
        <td>{{task.deadline}}</td>
        <td>{{task.topic_list}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</article>
<hx-get="?{{querystring}}" hx-swap="afterend" hx-target="#page{{page_obj.number}}"  hx-select="#page{{page_obj.number|add:1}}" hx-swap-oob="true" id="nextPage" hx-trigger="click once">

{% endblock %}