src/events/urls.py
from django.urls import path

from events.views import (CategoryAutoComplete, EventAction, EventCreate,
                          EventDelete, EventDetail, EventList, EventUpdate,
                          PostcodeAutoComplete)

app_name = 'events'

urlpatterns = [
    path("categories/",
         CategoryAutoComplete.as_view(),
         name="category_autocomplete"),
    path("postcodes/",
         PostcodeAutoComplete.as_view(),
         name="postcode_autocomplete"),
    path("create/", EventCreate.as_view(), name="event_create"),
    path("<int:pk>/", EventDetail.as_view(), name="event_detail"),
    path("<int:pk>/action/", EventAction.as_view(), name="event_action"),
    path("<int:pk>/update/", EventUpdate.as_view(), name="event_update"),
    path("<int:pk>/delete/", EventDelete.as_view(), name="event_delete"),
    path("", EventList.as_view(), name="event_list"),
]

src/news/urls.py
from django.urls.conf import path

from news.views import NewsItemDetail, NewsItemList

app_name = "news"

urlpatterns = [
    path("<int:pk>/", NewsItemDetail.as_view(), name="newsitem_detail"),
    path("", NewsItemList.as_view(), name="newsitem_list"),
]

src/proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('django_auth_oidc.urls')),
    path('app/', include("dashboard.urls")),
    path("app/events/", include("events.urls", 'events')),
    path("app/news/", include("news.urls", 'news')),
    path("app/tasks/", include("tasks.urls", 'tasks')),
    path('', include("events.external_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/events/models.py
import uuid

from address.models import AddressField
from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls.base import reverse
from django.utils.translation import gettext_lazy as _
from imagefield.fields import ImageField

from events.utils import sign_url

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("category"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Postcode(models.Model):
    zip_code = models.CharField(max_length=10,
                                unique=True,
                                verbose_name=_("zip code"))
    name = models.CharField(max_length=80)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return str(self.zip_code) + " " + self.name


class Event(models.Model):
    DRAFT = 0
    IN_REVIEW = 1
    PUBLISHED = 2
    DELETED = 3

    EVENT_STATES = (
        (DRAFT, _("draft")),
        (IN_REVIEW, _("review")),
        (PUBLISHED, _("published")),
        (DELETED, _("deleted")),
    )
    title = models.CharField(max_length=255, verbose_name=_("title"))

    start_date = models.DateTimeField(verbose_name=_("start date"))
    end_date = models.DateTimeField(verbose_name=_("end date"))

    description = RichTextField(verbose_name=_("description"))

    url = models.URLField(blank=True)

    address = AddressField(blank=True, null=True, verbose_name=_("address"))

    image = ImageField(verbose_name=_("image"),
                       blank=True,
                       auto_add_fields=True,
                       formats={
                           'preview': ['default', ('crop', (1200, 630))],
                           'square': ['default', ('crop', (400, 400))]
                       })

    state = models.IntegerField(choices=EVENT_STATES,
                                default=0,
                                verbose_name=_("state"))

    managers = models.ManyToManyField(get_user_model(),
                                      related_name="managed_events",
                                      blank=True,
                                      verbose_name=_("managers"))
    owner = models.ForeignKey(get_user_model(),
                              models.CASCADE,
                              related_name="owned_events",
                              verbose_name=_("owner"))

    rocket_chat = models.CharField(max_length=45,
                                   blank=True,
                                   verbose_name=_("chat"))

    categories = models.ManyToManyField(Category,
                                        verbose_name=_("categories"),
                                        blank=True)
    is_online = models.BooleanField(default=False, verbose_name=_("is online"))
    is_offline = models.BooleanField(default=False,
                                     verbose_name=_("is offline"))

    internal_id = models.UUIDField(default=uuid.uuid4)
    internal_note = RichTextField(verbose_name=_("internal note"), blank=True)

    @property
    def chat_link(self):
        return settings.ROCKET_CHAT_BASE + self.rocket_chat

    def signed_map_url(self, size):
        return sign_url(self.map_image_url(size))

    def map_image_url(self, size):
        return (
            "https://maps.googleapis.com/maps/api/staticmap"
            f"?markers=color:red|{self.address.latitude},{self.address.longitude}"
            f"&zoom=12&size={size}&key={settings.GOOGLE_API_KEY}")

    def map_url(self):
        return f"https://www.google.com/maps/search/?api=1&query={self.address.latitude},{self.address.longitude}"

    class Meta:
        verbose_name = _("event")
        verbose_name_plural = _("events")
        ordering = ['-start_date']
        permissions = [
            ("publish_event", _("Can publish an event.")),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('events:event_detail', args=(self.pk, ))


class AccessRequest(models.Model):
    user = models.ForeignKey(get_user_model(),
                             models.CASCADE,
                             verbose_name=_("user"))
    event = models.ForeignKey(Event, models.CASCADE, verbose_name=_("event"))
    created_at = models.DateTimeField(verbose_name=_("created"),
                                      auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'event'],
                                    name="one_request_per_user")
        ]

src/events/forms.py
from ckeditor.fields import RichTextFormField
from dal import autocomplete
from django import forms
from django.utils.translation import gettext as _
from html_sanitizer.django import get_sanitizer

from events.models import AccessRequest, Category, Event, Postcode


class EventForm(forms.ModelForm):
    def clean_description(self):
        return get_sanitizer().sanitize(self.cleaned_data['description'])

    def clean_internal_note(self):
        return get_sanitizer().sanitize(self.cleaned_data['internal_note'])

    class Meta:
        model = Event

        fields = [
            'title',
            'start_date',
            'end_date',
            'description',
            'url',
            'is_online',
            'is_offline',
            'address',
            'image',
            'managers',
            'categories',
            'rocket_chat',
        ]

        widgets = {
            'start_date':
            forms.SplitDateTimeWidget(
                date_format="%Y-%m-%d",
                date_attrs={'type': 'date'},
                time_attrs={'type': 'time'},
            ),
            'end_date':
            forms.SplitDateTimeWidget(
                date_format="%Y-%m-%d",
                date_attrs={'type': 'date'},
                time_attrs={'type': 'time'},
            ),
            'managers':
            autocomplete.ModelSelect2Multiple(
                url="dashboard:user-autocomplete"),
            'categories':
            autocomplete.ModelSelect2Multiple(
                url="events:category_autocomplete", )
        }

        field_classes = {
            'start_date': forms.SplitDateTimeField,
            'end_date': forms.SplitDateTimeField,
        }


class SelectAcceptRequestForm(forms.Form):
    access_request = forms.ModelChoiceField(AccessRequest.objects.all(), )


class FilterForm(forms.Form):
    search = forms.CharField(required=False)
    is_online = forms.NullBooleanField(
        label=_("type"),
        required=False,
        widget=forms.Select(choices=[
            ('', '--'),
            (True, _('online')),
            (False, _('offline')),
        ]),
    )
    start_date = forms.DateField(required=False,
                                 label=_("after"),
                                 widget=forms.DateInput(format="%Y-%m-%d",
                                                        attrs={'type':
                                                               'date'}))
    end_date = forms.DateField(required=False,
                               label=_("before"),
                               widget=forms.DateInput(format="%Y-%m-%d",
                                                      attrs={'type': 'date'}))
    zip_code = forms.ModelChoiceField(
        queryset=Postcode.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(url="events:postcode_autocomplete"),
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(url="events:category_autocomplete"),
    )

    def clean(self):
        if self.cleaned_data['start_date'] and self.cleaned_data[
                'end_date'] and self.cleaned_data[
                    'start_date'] > self.cleaned_data['end_date']:
            self.add_error('start_date',
                           _("start date has to be before end date"))

src/events/views.py
from dal import autocomplete
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import (SearchHeadline, SearchQuery,
                                            SearchRank, SearchVector)
from django.db.models.expressions import F, Value
from django.db.models.query_utils import Q
from django.shortcuts import redirect
from django.urls.base import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from dashboard.utils import ActionView
from events.actions import (AcceptRequest, DeleteRequest, PublishEvent,
                            RequestAccessAction, UnpublishEvent,
                            can_edit_event)
from events.forms import EventForm, FilterForm
from events.models import AccessRequest, Category, Event, Postcode

# Create your views here.


class EventList(ListView):
    model = Event
    paginate_by = 5

    def get_queryset(self):
        search = self.request.GET.get('search')
        zip_code = self.request.GET.get('zip_code')

        if self.request.user.is_authenticated:
            queryset = super().get_queryset().filter(
                end_date__gte=timezone.now(), )
        else:
            queryset = super().get_queryset().filter(
                state=Event.PUBLISHED,
                end_date__gte=timezone.now(),
            )

        self.filter_form = FilterForm(self.request.GET)
        self.filter_form.is_valid()

        search_data = self.filter_form.cleaned_data

        if search := search_data.get('search'):
            query = SearchQuery(search)
            vector = SearchVector('description', weight="A") + SearchVector(
                'title', weight="B")
            queryset = queryset.annotate(
                rank=SearchRank(vector, query),
                headline=SearchHeadline(
                    'description',
                    query,
                    start_sel="<em>",
                    stop_sel="</em>",
                    max_words=40,
                    min_words=20,
                ),
            ).order_by('-rank')

        online = search_data.get('is_online')
        if online is not None:
            if online:
                queryset = queryset.filter(is_online=True)
            else:
                queryset = queryset.filter(is_offline=True)

        if start_date := search_data.get("start_date"):
            queryset = queryset.filter(end_date__date__gte=start_date)

        if end_date := search_data.get("end_date"):
            queryset = queryset.filter(start_date__date__lte=end_date)

        if code := search_data.get('zip_code'):
            latitude = code.latitude
            longitude = code.longitude

            queryset = queryset.annotate(
                delta_lat=F('address__latitude') - Value(latitude),
                delta_lon=F('address__longitude') - Value(longitude),
            ).annotate(distance=F('delta_lat') * F('delta_lat') +
                       F('delta_lon') * F('delta_lon')).order_by('distance')

        if category := search_data.get('category'):
            queryset = queryset.filter(categories=category)

        return queryset

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['filter_form'] = self.filter_form
        if data['page_obj'].has_next():
            get_query = self.request.GET.copy()
            get_query['page'] = data['page_obj'].number + 1

            data['querystring'] = get_query.urlencode()

        return data


class ExternalEventList(EventList):

    template_name = 'events/external_event_list.html'


class EventDetail(DetailView):
    model = Event

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return super().get_queryset().filter(
                end_date__gte=timezone.now(), )
        else:
            return super().get_queryset().filter(
                state=Event.PUBLISHED,
                end_date__gte=timezone.now(),
            )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['title'] = self.get_object().title
        data['can_edit'] = can_edit_event(self.get_object(), self.request.user)

        if data['can_edit']:
            data['access_requests'] = AccessRequest.objects.filter(
                event=self.get_object())

        return data


class ExternalEventDetail(EventDetail):
    template_name = 'events/external_event_detail.html'


class EventAction(ActionView):
    model = Event
    actions = {
        'publish': PublishEvent,
        'unpublish': UnpublishEvent,
        'access': RequestAccessAction,
        'accept': AcceptRequest,
        'decline': DeleteRequest,
    }

    def get_queryset(self):
        return super().get_queryset()


@method_decorator(login_required, name='dispatch')
class EventCreate(SuccessMessageMixin, CreateView):
    model = Event
    success_message = _("%(title)s was created successfully")

    form_class = EventForm

    def dispatch(self, *args, **kwargs):
        response = super().dispatch(*args, **kwargs)

        if response.status_code == 302:
            response['HX-Redirect'] = response.url

        return response

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class EventUpdate(SuccessMessageMixin, UpdateView):
    model = Event
    success_message = _("%(title)s was updated successfully")
    form_class = EventForm

    def get_queryset(self):
        return super().get_queryset().filter(
            Q(owner=self.request.user)
            | Q(managers=self.request.user))


@method_decorator(login_required, name='dispatch')
class EventDelete(SuccessMessageMixin, DeleteView):
    model = Event

    success_message = _("%(title)s was deleted")
    success_url = reverse_lazy('events:event_list')


@permission_required('events.publish_event')
def publish_event(request, pk):
    if request.method == 'POST':
        Event.objects.filter(pk=pk).update(state=Event.PUBLISHED)
    return redirect('events:event_detail', pk)


class CategoryAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if self.q:
            return Category.objects.filter(name__icontains=self.q)

        return Category.objects.all()[:30]


class PostcodeAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if self.q:
            return Postcode.objects.filter(
                Q(zip_code__startswith=self.q)
                | Q(name__icontains=self.q))[:30]
        return Postcode.objects.none()

src/events/templates/events/event_detail.html
{% extends "dashboard/base.html" %}
{% load i18n l10n %}

{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.17.0/codemirror.css" />
<link rel="stylesheet" href="https://firepad.io/releases/v1.5.10/firepad.css" />

<style>
#notePad {
  height: 100%;
  min-height: 30em;
}
.firepad {
  width: 100%;
  height: 100%;
  background-color: #000; 
  border: solid black 1px;
}

.powered-by-firepad {
  display: none;
}
</style>
{% endblock %}


{% block breadcrumbs %}
<a href="{% url 'events:event_list' %}">{% trans 'Events' %}</a> / {{event.title}}
{% endblock %}

{% block actions %}
<form action="{% url 'events:event_delete' event.pk %}" method="post" onsubmit="return confirm('{% trans 'Are you sure you want to delete this event?' %}')">
  {% csrf_token %}
  <button class="button delete">
    <i data-feather="trash"></i>
    {% trans 'Delete' %}
  </button>
</form>
{% if can_edit %}
<a class="button update"  href="{% url 'events:event_update' event.pk %}">
  <i data-feather="edit"></i>
  {% trans 'Update' %}
</a>
{% if perms.events.publish_event %}
{% if event.state != event.PUBLISHED %}
<button class="button publish" hx-post="{% url 'events:event_action' event.pk %}?action=publish" hx-headers='{"X-CSRFToken": "{{csrf_token}}"}' hx-target="#pageContent" hx-swap="outerHTML" hx-select="#pageContent">
  <i data-feather="check"></i>
  {% trans 'Publish' %}
</button>
{% else %}
<button class="button unpublish" hx-post="{% url 'events:event_action' event.pk %}?action=unpublish" hx-headers='{"X-CSRFToken": "{{csrf_token}}"}' hx-target="#pageContent" hx-swap="outerHTML" hx-select="#pageContent">
  <i data-feather="x"></i>
  {% trans 'Unpublish' %}
</button>
{% endif %}
{% endif %}
{% else %}
<button class="button access" hx-post="{% url 'events:event_action' event.pk %}?action=access" hx-headers='{"X-CSRFToken": "{{csrf_token}}"}' hx-target="#pageContent" hx-swap="outerHTML" hx-select="#pageContent">
  <i data-feather="x"></i>
  {% trans 'Request access' %}
</button>
{% endif %}
{% endblock %}

{% block page_content %}

<article class="eventDetail">
  {% if can_edit and access_requests %}
  {% for access_request in access_requests %}
  <div class="accessRequest">
    <span class="accessName">{{access_request.user.get_full_name}}</span>
    <div class="accesActions">
      <button class="button access" hx-post="{% url 'events:event_action' event.pk %}?action=accept" hx-headers='{"X-CSRFToken": "{{csrf_token}}"}' hx-target="#pageContent" hx-swap="outerHTML" hx-select="#pageContent" hx-vals='{"access_request": "{{access_request.pk}}"}'>
        <i data-feather="x"></i>
        {% trans 'Accept' %}
      </button>
      <button class="button access" hx-post="{% url 'events:event_action' event.pk %}?action=decline" hx-headers='{"X-CSRFToken": "{{csrf_token}}"}' hx-target="#pageContent" hx-swap="outerHTML" hx-select="#pageContent" hx-vals='{"access_request": "{{access_request.pk}}"}'>
        {% trans 'Delete' %}</button>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  <div class="event-info">

  <div class="event-time">
    <time datetime="{{event.start_date|date:"c"}}">{{event.start_date}}</time> - <time datetime="{{event.end_date|date:"c"}}">{{event.end_date}}</time>
  </div>
    {% if event.address %}
    <div class="event-address">
      <a href="https://www.google.com/maps/search/?api=1&query={{event.address.latitude|unlocalize}},{{event.address.longitude|unlocalize}}" target="_blank">
        {{event.address}}
      </a>
    </div>
    {% endif %}

    {% if event.url %}
    <div class="event-link">
      <a href="{{event.url}}" target="_blank">{{event.url|truncatechars:40}}</a>
    </div>
    {% endif %}
  </div>

  <div class="text">
    {{event.description | safe}}
  </div>

    <a href="{% url 'external_events:event_detail' event.pk %}" target="_blank">{% trans 'View on Site' %}</a>

  <div class="shareInfo">
    <div class="copyLink">
      <label for="event_url">{% trans 'click to copy' %}</label>
      <input type="text" value="{{request.scheme}}://{{request.get_host}}{% url 'external_events:event_detail' event.pk %}" onclick="this.select();document.execCommand('copy');" readonly id="event_url"/>
    </div>
  </div>

  <section class="internal">
    {% if event.rocket_chat %}
    <div class="chat">
      <h2><a href="{{event.chat_link}}" target="_blank">{% trans 'Chat' %}</a></h2>
      <iframe id="rocket-{{event.rocket_chat}}"  class="chat" src="{{event.chat_link}}?layout=embedded"></iframe>
    </div>
    {% endif %}
    <div class="notes">
      <h2>{% trans 'Internal notes' %}</h2>
      <div id="notePad"></div>
    </div>
  </section>
</article>

{% endblock %}

{% block scripts %}
<script src="https://www.gstatic.com/firebasejs/7.6.2/firebase.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.17.0/codemirror.js"></script>
<script src="https://firepad.io/releases/v1.5.10/firepad.min.js"></script>
<script>
  function init() {
      var firebaseConfig = {
          apiKey: "AIzaSyCB0O2rIAPRN-Dk2Z5-MvhAB-tzaY4EJuU",
          authDomain: "initiative-99.firebaseapp.com",
          projectId: "initiative-99",
          databaseURL: "https://initiative-99.firebaseio.com",
          storageBucket: "initiative-99.appspot.com",
          messagingSenderId: "572830274278",
          appId: "1:572830274278:web:27b63965385f3257b02127"
        };
      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);

      // Get Firebase Database reference.
      var firepadRef = firebase.database().ref('events/{{event.internal_id}}');

      // Create CodeMirror (with lineWrapping on).
      var codeMirror = CodeMirror(document.getElementById('notePad'), { lineWrapping: true });

      // Create Firepad (with rich text toolbar and shortcuts enabled).
      var firepad = Firepad.fromCodeMirror(firepadRef, codeMirror, {
          richTextShortcuts: false,
          richTextToolbar: true,
          defaultText: 'Hier hat es Platz für Notizen.',
          // userId: "{{request.user.pk}}",
        });
    }

    window.addEventListener("load", init);
</script>
{% endblock %}

src/events/templates/events/event_form.html
{% extends 'dashboard/base.html' %}
{% load i18n %}

{% block breadcrumbs %}
{% if form.instance.pk %}
<a href="{% url 'events:event_list' %}">{% trans 'Events' %}</a> / <a href="{% url 'events:event_detail' event.pk %}">{{event.title}}</a> / {% trans 'Update' %}
{% else %}
<a href="{% url 'events:event_list' %}">{% trans 'Events' %}</a> / {% trans 'Create' %}
{% endif %}
{% endblock %}

{% block page_content %}
<form method="post" hx-push-url="false" enctype="multipart/form-data">
  {% include 'registration/form.html' %}
  <button type="submit" class="button">
    {% if form.instance.pk %}
    {% trans 'Update' %}
    {% else %}
    {% trans 'Create' %}
    {% endif %}
  </button>
</form>
{{form.media}}
{% endblock %}

src/events/templates/events/event_list.html
{% extends 'dashboard/base.html' %}
{% load i18n l10n %}

{% block title %}{% trans 'Events' %}{% endblock %}

{% block breadcrumbs %}
<a href="{% url 'events:event_list' %}">{% trans 'Events' %}</a>
{% endblock %}

{% block actions %}
<a class="button" href="{% url 'events:event_create' %}">{% trans 'Create' %}</a>
{% endblock %}

{% block page_content %}
<form method="get" id="filterForm" action="">
  {% for field in filter_form %}
  <div class="formField">
    <label>{{ field.label }}</label>
    {{ field }}
  </div>
  {% endfor %}
  <button type="submit">Los</button>
</form>
<article id="eventList" class="events">
  <div  id="page{{page_obj.number}}">
    {% for event in event_list %}
    <section >
      <h2>
        <a href="{{event.get_absolute_url}}" >{{event.title}}</a>
      </h2>
      <div class="event-info">
        <div class="event-time">
          {{event.start_date}} - {{event.end_date}}
        </div>
        {% if event.address %}
        <div class="event-address">
          <a href="https://www.google.com/maps/search/?api=1&query={{event.address.latitude|unlocalize}},{{event.address.longitude|unlocalize}}" target="_blank">
            {{event.address}}
          </a>
        </div>
        {% endif %}
        {% if event.url %}
        <div class="event-link">
          <a href="{{event.url}}" target="_blank">{{event.url|truncatechars:40}}</a>
        </div>
        {% endif %}
      </div>
      <div class="event-content">
        {{event.description | safe | truncatechars_html:240}}
      </div>
    </section>
    {% endfor %}

  </div>
  {% if page_obj.has_next %}
  <button onclick="this.blur()" hx-get="?{{querystring}}" hx-swap="afterend" hx-target="#page{{page_obj.number}}"  hx-select="#page{{page_obj.number|add:1}}" hx-swap-oob="true" id="nextPage" hx-trigger="click once">Next</button>

  {% endif %}
</article>
{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{{filter_form.media}}
{% endblock %}

src/events/templates/events/external_event_detail.html
{% extends 'base.html' %}
{% load i18n events l10n %}

{% block title %}{{event.title}} | we-are-the-99.ch{% endblock %}

{% block page_content %}
<article class="event detail">
  <div class="eventDescription">
    <h2>
      <a href="{% url 'external_events:event_detail' event.pk %}" >{{event.title}}</a>
    </h2>
    <div class="event-info">
      <div class="event-time">
        {{event.start_date}} - {{event.end_date}}
      </div>
      {% if event.address %}
      <div class="event-address">
        <a href="{{event.map_url}}" target="_blank">
          {{event.address}}
        </a>
      </div>
      {% endif %}
    </div>
    <div class="event-content">
      {{event.description | safe }}
    </div>

    {% if event.url %}
    <div class="event-link">
      <a href="{{event.url}}" target="_blank">{{event.url|truncatechars:40}}</a>
    </div>
    {% endif %}

    <a href="{% url 'external_events:event_list' %}" class="button">
      {% trans 'All events' %}
    </a>
    <a href="{% url 'events:event_detail' event.pk %}" class="button">
      {% trans 'Event admin' %}
    </a>
  </div>
  <div class="eventImage">
    {% if event.address %}
    <a href="{{event.map_url}}" target="_blank">
      <img src="{{event|staticmap:"600x400"}}" />
    </a>
    {% endif %}
    {% if event.image %}
      <img src="{{event.image.preview}}" />
    {% endif %}
    <div class="shareButtons">
      <a target="_blank" class="button" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Facebook</a>
      <a target="_blank" class="button" href="https://api.whatsapp.com/send?text={{request.build_absolute_uri}}">Whatsapp</a>
      <a target="_blank" class="button" href="https://twitter.com/intent/tweet?url={{request.build_absolute_uri}}">Twitter</a>
    </div>
  </div>
</article>
{% endblock %}